### ISSUE TITLE
Vast majority of people on the list are not actually transphobic.

### ISSUE THREAD

**Issue by liberninja** [bethylamine/twitter-archives#10]
Vast majority of people on the list are not actually transphobic. Just a minor bug 😂

**Comment by Silanael** [comment]
It's not a bug, it's a feature.

**Comment by GeneralAwareness** [comment]
I have never had an irrational fear of a transgendered person.  I am still looking for such a person, then when I find them I can actually slap this label on them.  Until then anyone using such a term as "transphobic": just shows how utterly idiotic they are.  Get some science, you damn dirty apes.
