### ISSUE TITLE
How do I get added to the list

### ISSUE THREAD

**Issue by lotus49** [bethylamine/twitter-archives#11]
My friends are boasting that they are on your TERF list and I'm not.  I'm a TERF so how do I get my name added to the list?

**Comment by caldodge** [comment]
Just tweet "reality is transphobic", as I do.  (I'm currently number 6053)

**Comment by Mustikkamunkki** [comment]
You gotta terf harder 🤣 

Or

clone the repository, add your handle to the file and create a pull request to add your changes to the repository.

**Comment by MrEnigma28** [comment]
Yo I wanna be added to the list!! #TransRightsIsPrivilege
