### ISSUE TITLE
Role description

### ISSUE THREAD

**Issue by sergrahi** [bethylamine/twitter-archives#14]
A bit of background on the members of this Great Inquisition could be interesting to add.
And we should include next steps, for example but not limited to:
- Dates of trial.
- Tests to pass, i.e., throwing them down a cliff and checking if an angelical trans save them or not.
- Place for burning alive the guilty ones: a Major Square in a big city is preferred.

**Comment by Maybelle1994** [comment]
You’re very sick.

**Comment by use10year** [comment]
the real tests we should be doing is on how to fix gender dysphoria so people can be happy in their biological, real body.
its a mental disorder and the treatment is physical, think about that..
