### ISSUE TITLE
GDPR violation and risk of sanction or ban in Europe

### ISSUE THREAD

**Issue by aeris** [bethylamine/twitter-archives#18]
Hello,

Even if I totally support LGBT rights and transphobia fight, given there is European people in this list, I need to warn here such a list of transphobic people are currently in huge violation of GDPR law (article 6, 12, 14 and 21) and you currently face a European ban, 20 millions € administrative fine and (at least in France) 5 years jail + 375 000€ penal fine.

Shinigamy Eyes extension, which have the same purpose this repository but with many more technical protection (bloom filter usage) to avoid raw name listing was currently stroke by Norway Data Protection Agency and ban in the country.

https://github.com/shinigami-eyes/shinigami-eyes/issues/79
https://www.datatilsynet.no/contentassets/af7627c042ec4ad39d8bd67527f02aae/advance-notification-of-a-ban-on-processing--shinigami-eyes.pdf

**Comment by use10year** [comment]
username scraping moment
but username scraping is against GDPR? isnt it publicly available information?
afaik this isnt breaking GDPR..

**Comment by aeris** [comment]
Scrapping is against GDPR. The fact information is public or not doen't change the violation.
ClearView was fine 59 millions euros exactly for that from 9 differents DPA.

**Comment by bethylamine** [comment]
Is creating Twitter lists also a violation of GDPR? Say, a public twitter list with 40,000 users on it? Asking for a friend.

**Comment by bethylamine** [comment]
Or automated blocklists that are available and continue to run? https://github.com/jdbillingham/blocktogether

**Comment by bethylamine** [comment]
![FF8848C2-6740-492E-8B7F-3752F13BEC25](https://user-images.githubusercontent.com/130214958/234760902-daef0599-da71-4de7-89ca-001362b94596.jpeg)

**Comment by aeris** [comment]
Yes, creating a Twitter list is violating the GDPR, at least as soon as the list is publicly available.
Til it stay private, you have the 2(2)c "strictly household exception" apply and so no GDPR at all, but if publicly available, full GDPR compliance needed.

**Comment by aeris** [comment]
Something still running is not a proof of no GDPR violation.
You also need somebody to act against it on a DPA case and wait for the DPA decision which can be very long (more than 5 years in France for example).
And even after that, we still have Shimanagi Eyes available everywhere but Norway but it's technically illegal in all Europe because article 64 of GDPR which enforce European coherence and a national DPA decision applicable in the 27 others EU country. Legally, we just have to open a case on each 27 other DPA and we are mostly ensure to have full block at the end because no DPA can act against the Norway decision and all must take the same action.

**Comment by aeris** [comment]
The screenshot is just totally non sense. "The GDPR investigate my old block list". A DPA can investigate. EDPB can investigate. A judge can investigate. "GDPR" is not a person nor an entity and can't investigate.
And if there is such DPA decision, perhaps we can list it on https://gdprhub.eu/ or https://enforcementtracker.com/ which list every know DPA decision even the most short one?

**Comment by jdbillingham** [comment]
The UK Data Protection agency, ICO, investigated @TheBlockBot a few years back. Decided even though I was hosting it and created the tool it was outside of the scope of the DPA (At the time) as the data controllers were based in the US and Australia. It was ruled that a blocklist could come under the scope of data protection when managed by a group of people in the EU. 

The Shingami eyes decision looks daft to me, but what effect has it had? Shinigami Eyes is still running, still available in Norway as they can't regulate the entire internet over their own bad interpretation of how being marked as "anti-trans" might effect someone. So all this scaremongering over fines and prison time (lol!) makes you look extremely bad faith. (@oolon)

**Comment by jdbillingham** [comment]
"Technically" doing a lot of heavy lifting there. Maybe it's your style but that sort of scaremongering isn't helpful. 

The decision on @TheBlockBot was before GDPR, so isn't particularly useful. I got the impression they wished it would go away, but a bunch of internet trolls were organising complaints so they had to do an investigation. Someone's personal coding project, as in Beth's here, is going to be of even less interest to them. But I would advise her to stay anonymous as regardless of the technicalities of the GDPR, terfs and trolls could cause her a lot of stress with complaints. If her anon bot gets marked as "illegal" in Norway then add it to the Twitter bio as a mark of pride and how daft petty bureau/eurocrats are.

**Comment by jdbillingham** [comment]
Realised github is linking my @/theblockbot to a repo, I mean the Twitter account :D

**Comment by aeris** [comment]
"Personal coding project" is not a pretext to violate basic law about data protection existing since 1950 in Europe (HREC 1950, ePrivacy 1995, LCEN 1978, GDPR 2016), even if you think to be on the light side of the force.

**Comment by bethylamine** [comment]
Thanks for your concern. I will not be taking any legal advice from this thread and will instead confer with lawyers.

**Comment by aeris** [comment]
> For info, putting the database behind a password does not correct the problem, you have to declare the data collection to the CNIL (in France).
> The CNIL will give you a registration number that you must clearly expose, a data manager must be designated and his contact clearly indicated.

There is no more such mandatory declaration since 2016 and the GDPR publication :blush:

**Comment by RemiLelaidier** [comment]
> > For info, putting the database behind a password does not correct the problem, you have to declare the data collection to the CNIL (in France).
> > The CNIL will give you a registration number that you must clearly expose, a data manager must be designated and his contact clearly indicated.
> 
> There is no more such mandatory declaration since 2016 and the GDPR publication 😊
> 
> But yeah, even if not public, you need a valid and lawfull legal basis (here legitimate interest), and take action to ensure all GDPR articles are respected (in this case, the article 14 is hightly violated in such a list).

My bad, yeah you're right about the mandatory declaration
