### ISSUE TITLE
Massive violation of GDPR

### ISSUE THREAD

**Issue by Maybelle1994** [bethylamine/twitter-archives#20]
You’re in violation of the GDPR and I actually work for an organisation that deals in GDPR. You could be fined 20,000,000 and face jail time. I’d highly advise that you take this down.

**Comment by bethylamine** [comment]
You joined GitHub yesterday. A list of usernames is not in violation of GDPR.

**Comment by RemiLelaidier** [comment]
I work with the GDPR all day and yes, you are violating the GDPR.
You are creating a database, without the consent of the data subjects, for a use of which those data subjects are not even aware.

Fighting transphobia is important, but do it right.

For info, putting the database behind a password does not correct the problem, you have to declare the data collection to the CNIL (in France).
The CNIL will give you a registration number that you must clearly expose, a data manager must be designated and his contact clearly indicated.

And that, and I repeat, even if the data is not made public, ALL data collection must be declared, the use of this data clearly established and the persons concerned must have the right to be removed from your database.

**Comment by julien-lecomte** [comment]
> You joined GitHub yesterday. A list of usernames is not in violation of GDPR.

It is actually since it allows personal identification.
