### ISSUE TITLE
Missing purpose in life

### ISSUE THREAD

**Issue by DarkXSeries7** [bethylamine/twitter-archives#22]
This repository has no purpose, it consists of a malding creator adding a list of people they don't like for telling the truth. In fact, they are so insufferable, they spent time on this repository for a website they hate. Couldn't be me!

![20230420_122750.jpg](https://user-images.githubusercontent.com/68074009/234400563-7f3827dc-1337-4ca0-9a7e-d0ed2102c108.jpg)

**Comment by RDS5** [comment]
bro they made a whole twitter bot abt this shit 💀
